---
### Migration
- name: (Migration) check existence of the custom-journalctl-vacuum.service
  ansible.builtin.stat:
    path: "/etc/systemd/system/custom-journalctl-vacuum.service"
  register: custom_service
- name: (Migration) check existence of the custom-journalctl-vacuum.timer
  ansible.builtin.stat:
    path: "/etc/systemd/system/custom-journalctl-vacuum.timer"
  register: custom_timer
- name: (Migration) Ensure custom-journalctl-vacuum.service is stopped and disabled
  ansible.builtin.service:
    name: custom-journalctl-vacuum.service
    enabled: false
    state: stopped
  when: custom_service.stat.exists | bool
- name: (Migration) Ensure custom-journalctl-vacuum.timer is stopped and disabled
  ansible.builtin.service:
    name: custom-journalctl-vacuum.timer
    enabled: false
    state: stopped
  when: custom_timer.stat.exists | bool
- name: (Migration) Ensure custom-journalctl-vacuum units are removed
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}"
    state: absent
  with_items:
    - custom-journalctl-vacuum.service
    - custom-journalctl-vacuum.timer
  when: custom_service.stat.exists | bool or custom_timer.stat.exists | bool
### End migration

- name: Ensure systemd-journald-autovacuum units are installed
  ansible.builtin.template:
    src: "systemd/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - systemd-journald-autovacuum.timer
    - systemd-journald-autovacuum.service

- name: Esure systemd-journald-autovacuum units are enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
    state: started
  with_items:
    - systemd-journald-autovacuum.service
    - systemd-journald-autovacuum.timer
