---
- name: Ensure thumbnails are removed
  ansible.builtin.file:
    path: "{{ matrix_synapse_media_store_path }}/{{ item }}"
    state: absent
  with_items:
    - local_thumbnails
    - remote_thumbnail
    - url_cache_thumbnails
  when: system_cleanup_matrix_thumbnails | bool and matrix_synapse_enabled | bool and matrix_synapse_media_store_path is defined
  ignore_errors: true
