---

roles:
  - src: https://github.com/geerlingguy/ansible-role-docker
    version: 8.0.0
    name: ansible-role-docker
collections:
  # What Molecule's own Docker driver needs in order to create and destroy the
  # test container.
  - name: community.docker
    version: 5.2.2
